
		.section	.bss

		.comm		storyptr, 2
		.comm		storybits, 1
		.comm		storywait, 2

		.comm		songptr, 2
		.comm		songbits, 1
		.comm		ch, 3*18
		.comm		noisevolume, 1
		.comm		noiserelease, 1
		.comm		tracktimer, 1
		.comm		trackpos, 1

		.comm		vbltime, 1
		.comm		framecount, 2
		.comm		linehandler, 1
		.comm		copperptr, 2

		.comm		bg, 1
		.comm		palette, 4

		.comm		text, 25
		.comm		texty, 25
		.comm		scrollx, 1

		;.comm		horizon, 1

		.comm		timer3, 1

		.comm		copperlist, 2*16

		.comm		vblvector, 1
		.comm		mlvector, 1

		.comm		scrollptr, 2
		.comm		scrollbits, 1

		.comm		twist, 1

		.comm		tunneloffset, 1

		.comm		xoffset, 1

		.comm		crednum, 1

