@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"E:\iar\arm\common\bin\cspybat" "E:\iar\arm\arm\bin\armproc.dll" "E:\iar\arm\arm\bin\armjlink.dll"  %1 --plugin "E:\iar\arm\arm\bin\armbat.dll" --backend -B "--endian=little" "--cpu=ARM7TDMI" "--fpu=None" "-p" "E:\iar\arm\arm\CONFIG\debugger\Atmel\ioAT91SAM7S512.ddf" "--semihosting" "--device=AT91SAM7S512" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--drv_restore_breakpoints=_call_main" 


