extern const int FurElise[];
extern const int Mozart[];
extern const int Minuet[];
extern const int Sirene1[];
extern const int AuldLangSyne[];
extern const int Sirene2[];
extern const int Whistle[];
extern const int Invent8[];
extern const int Fugue[];
